### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by erwinvaneyk** [erwinvaneyk/Dragons-Arena#30]
### High prio:

**System operation requirements**:
- [x] Fix the Game Trace Archive workload manager
- Import data: count matches (they should be deleted after ~1 hour)
- Based on the number of matches add or remove units to the game. (Maybe not 1:1 because 1000 units would not fit on the board)
- To keep the game ongoing, respawn units if they die
- [x] Make sure we have a working game
- [x] Check if synchronization is working correctlly

**Fault tolerance**:
- [x] Make sure that a disconnected client does not cause problems
- [x] Make sure that a disconnected server does not cause problems, clients should contact other servers
- [x] Check if logs are correctly stored using two nodes

**Scalability requirements**:
- [x] implement a seamless node redirect during runtime
- [x] implement node rebalancing
- [x] Test with 100 Players and 20 Dragons on 5 servers

### Low prio:
 - [x] decrease number of heartbeats to only heartbeat nodes that havent been heart from a while
